### ISSUE TITLE
UI design Vers1

### ISSUE THREAD

**Issue by qyc206** [ca-chow/DesktopPet_Eui#14]
- [x] create a new balsamiq project on Google Drive
- [x] wireframe
- [x] sketch of physical interface
- [x] walkthrough of user flow with justification w.r.t. UX design principles

**Comment by casychow** [comment]
![image](https://user-images.githubusercontent.com/58012214/112059892-da2dea80-8b32-11eb-82f8-625c20fa4b6a.png)

forgot to add wireframe screen after lab

**Comment by casychow** [comment]
Home page
![image](https://user-images.githubusercontent.com/58012214/112347169-0c5b5b80-8c9d-11eb-8b4c-65d694dcbcba.png)

Register page
![image](https://user-images.githubusercontent.com/58012214/112347318-1da46800-8c9d-11eb-97cb-ee338b6b324d.png)

Help for serial code
![image](https://user-images.githubusercontent.com/58012214/112347388-31e86500-8c9d-11eb-84fe-26aabb25392e.png)

Forgot username/password
![image](https://user-images.githubusercontent.com/58012214/112347501-49bfe900-8c9d-11eb-8d9d-2791050aff03.png)

Reset password
![image](https://user-images.githubusercontent.com/58012214/112347564-5b08f580-8c9d-11eb-8ba0-cf13e604d988.png)

Logged in home page
![image](https://user-images.githubusercontent.com/58012214/112347728-7e33a500-8c9d-11eb-89bc-858ea45a741b.png)

Saved info page
![image](https://user-images.githubusercontent.com/58012214/112347661-6eb45c00-8c9d-11eb-981e-4e243fc8ffc3.png)

**Comment by casychow** [comment]
Split the registration page into 2 pages. That way we could also ask the user for the product' serial number and then ask the user how they would like to register: email, Facebook, Google, or Twitter.

Serial number page:
![image](https://user-images.githubusercontent.com/58012214/112355774-5dbb1900-8ca4-11eb-9ffa-55bdab2ef609.png)

Email address registration page:
![image](https://user-images.githubusercontent.com/58012214/112355875-77f4f700-8ca4-11eb-885a-3b7c47cc5000.png)

**Comment by casychow** [comment]
Qin Ying and I filled in each wireframe's justification in this google doc link: https://docs.google.com/document/d/1fp2OqQjdFG1uZvswCUm9oU50fRxpDpFbMWxLChRLKwk/edit?usp=sharing
