### ISSUE TITLE
testing edge detection subsystem

### ISSUE THREAD

**Issue by qyc206** [ca-chow/DesktopPet_Eui#4]
- [x] is it dead? check if it turns on with power
- [x] connect to pi
- [x] check if we can get a response
- [x] fill in readDist() and read some distances 
- [x] verify accuracy of sensor
- [x] mount it onto robot or something of similar distance away from table
- [x] manually move over tables edges and check readings

**Comment by qyc206** [comment]
Tested ADC MCP3004 with known reference voltages (gnd and 3.3V)
Code:
<img width="565" alt="Screen Shot 2021-03-31 at 5 06 30 PM" src="https://user-images.githubusercontent.com/60202147/113212066-47810000-9244-11eb-9748-bf61259aca6b.png">
Result:
<img width="525" alt="Screen Shot 2021-03-31 at 5 06 48 PM" src="https://user-images.githubusercontent.com/60202147/113212086-4fd93b00-9244-11eb-913e-b3f0b6c5f501.png">


CURRENT STATUS: does not seem to be sensing/detecting changes in distance (only detects one value... 0V when ADC read value is converted to voltage) 

Code:
<img width="743" alt="Screen Shot 2021-03-31 at 5 09 46 PM" src="https://user-images.githubusercontent.com/60202147/113212158-64b5ce80-9244-11eb-911b-fc0c6fdb2ee9.png">
Current wiring:
![IMG_4341](https://user-images.githubusercontent.com/60202147/113210494-4cdd4b00-9242-11eb-9258-68d4565462ec.JPG)

Resource:
<img width="608" alt="Screen Shot 2021-03-31 at 4 57 13 PM" src="https://user-images.githubusercontent.com/60202147/113210533-5a92d080-9242-11eb-87d2-d151910095eb.png">
https://www.instructables.com/Using-IR-Sensor-TCRT-5000-With-Arduino-and-Program/

**Comment by qyc206** [comment]
Current status: still doesn't work.. :'( Wiring has been changed to the following

![IMG_4355](https://user-images.githubusercontent.com/60202147/113908924-1bfe9800-97a5-11eb-8547-3c54ca2a3d4d.JPG)

**Comment by casychow** [comment]
Needed to find my pi's new ip address before accessing VNC viewer. This is the output when the C0 is connected to 3.3V.
![image](https://user-images.githubusercontent.com/58012214/115122060-eff0cd00-9f83-11eb-80b6-0d901dc59d2d.png)

This is the output when C0 is connected to GND.
![image](https://user-images.githubusercontent.com/58012214/115122092-1282e600-9f84-11eb-97a6-53b7197c5c62.png)

Followed CompEDP1 [lab 12 manual instructions](https://newclasses.nyu.edu/access/lessonbuilder/item/30283206/group/86d56136-af31-4022-8a4b-4b576154cc7a/Lessons/12:%20ADC,%20multiplexing/adc.pdf) and used the [MCP3004 datasheet](https://newclasses.nyu.edu/access/lessonbuilder/item/30283191/group/86d56136-af31-4022-8a4b-4b576154cc7a/Lessons/12:%20ADC,%20multiplexing/MCP3004.pdf) to wire the circuit.

I only get the following message even after adding an LED like most online [tutorials](https://www.14core.com/wiring-with-tcrt5000-reflective-optical-sensor-module-on-raspberry-pi/) recommend. This value is consistent no matter if I shine light directly onto the digital sensor or not.
![image](https://user-images.githubusercontent.com/58012214/115130262-3eba5900-9fbc-11eb-91e2-3c6491954dd9.png)

I added a LED to the input of the digital sensor and wired the digital sensor output as the input to the ADC.
![image](https://user-images.githubusercontent.com/58012214/115130398-87264680-9fbd-11eb-9089-83c0785c2769.png)

**Comment by casychow** [comment]
My current code:
![image](https://user-images.githubusercontent.com/58012214/115130753-25b3a700-9fc0-11eb-8974-df4064294fda.png)

**Comment by casychow** [comment]
Moved circuit onto a bigger breadboard yesterday and started testing it today. The values on the distance sensor works but the values seem inconsistent.

This is my current circuit as of yesterday. The green wire is only for for testing purposes. It usually holds a value of 23mV. The voltage drop across the distance sensor is 0.2-0.3mV.
![image](https://user-images.githubusercontent.com/58012214/115155856-b38aa300-a04f-11eb-96f2-6a173727efc7.png)

This is the circuit schematic as of now. I think the issue lies in the 5kΩ I used to power the distance sensor's collector pin and/or the A pin of the digital sensor. Many resources say to connect it to a GPIO input, but I'm still not sure why.
![IMG_DCD2A914D7DF-1](https://user-images.githubusercontent.com/58012214/115157191-dc159b80-a055-11eb-8c62-02020734b2e6.jpeg)

**Comment by casychow** [comment]
Tried to change the pull down resistor but when using the following code, the digital sensor's readings dropped lower than expected.
![image](https://user-images.githubusercontent.com/58012214/115157385-f308bd80-a056-11eb-905c-178eb53f1b3a.png)
![image](https://user-images.githubusercontent.com/58012214/115157419-192e5d80-a057-11eb-9a2d-ca22bfbdacc7.png)

Replaced 5x 1kΩ resistors with a 4.7kΩ resistor.
Replaced GPIO16 and 100Ω resistor input to the A pin on the digital sensor with 100Ω resistor to ground and then removed a connected to the A pin altogether.

Resources:
spidev documentation - https://pypi.org/project/spidev/
spidev and ADC example - https://learn.sparkfun.com/tutorials/python-programming-tutorial-getting-started-with-the-raspberry-pi/experiment-3-spi-and-analog-input
distance measurement - https://tutorials-raspberrypi.com/infrared-distance-measurement-with-the-raspberry-pi-sharp-gp2y0a02yk0f/
https://jeremyblythe.blogspot.com/2012/09/raspberry-pi-distance-measuring-sensor.html?m=1
enable SPI - https://www.raspberrypi-spy.co.uk/2014/08/enabling-the-spi-interface-on-the-raspberry-pi/
tcrt5000 datasheet - https://www.vishay.com/docs/83760/tcrt5000.pdf
pull_up_down resistor - https://www.14core.com/wiring-with-tcrt5000-reflective-optical-sensor-module-on-raspberry-pi/

Asking prof for help on piazza
Current code
![image](https://user-images.githubusercontent.com/58012214/115163462-42f77c80-a077-11eb-995a-c13bfaad42bf.png)
![image](https://user-images.githubusercontent.com/58012214/115163485-5d315a80-a077-11eb-9dc9-96c688de4835.png)
![image](https://user-images.githubusercontent.com/58012214/115163514-7fc37380-a077-11eb-9db1-309ddb6511e2.png)

**Comment by casychow** [comment]
New circuit:
![IMG_997828A15854-1](https://user-images.githubusercontent.com/58012214/115187233-f7fa5b00-a0b0-11eb-90bf-14bdbf4b499c.jpeg)
![distancesensor](https://user-images.githubusercontent.com/58012214/115187253-fdf03c00-a0b0-11eb-8318-0be4588c9a74.jpeg)

Voltage and ADC values change as objects move closer/further away

Code:
![image](https://user-images.githubusercontent.com/58012214/115188536-0f3a4800-a0b3-11eb-8c21-c8bec37892c9.png)
![image](https://user-images.githubusercontent.com/58012214/115188595-237e4500-a0b3-11eb-9224-db249ed11945.png)
